import type { Metadata } from "next";
import { Geist_Mono, Exo_2 } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/nav-bar";
import { ThemeProvider } from "next-themes";
import { locales } from "../i18n";
import { getDictionary } from '../i18n'
import { I18nProvider } from '../i18n/context'


const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ['400', '500', '700'],
  variable: '--font-exo2'
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params
  const dict = await getDictionary(locale)

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${exo2.variable} ${geistMono.variable} antialiased `}
      >
        <ThemeProvider attribute={'class'}>
          <I18nProvider dict={dict} locale={locale}>

            <NavBar />
            <main className=" max-w-7xl mx-auto px-4 py-8">
              {children}
            </main>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
